# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash

set -e

# Usage: ./deploy.sh [branch]
BRANCH="${1:-main}"  # Default to 'main' if not provided

echo "Checking out branch '$BRANCH' for main repo and submodules..."

# Checkout the desired branch in the main repo
git fetch origin "$BRANCH"
git checkout "$BRANCH"

# Initialize submodules if needed
git submodule init

# Update submodules to the specified branch
git submodule update --recursive --remote

# Checkout the specified branch in each submodule
git submodule foreach --recursive "
    git fetch origin $BRANCH || true
    git checkout $BRANCH || true
"

echo "Checked out branch '$BRANCH' for main repo and submodules."


# Run the script as deploy.sh <branchname>
